#!/bin/bash
# Setup script for n8n + CLI Tools
# Generates .env file with secure credentials
#
# Usage:
#   ./setup.sh           # Development setup
#   ./setup.sh --prod    # Production setup (with domain/SSL config)

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check for production flag
PROD_MODE=false
if [ "$1" = "--prod" ] || [ "$1" = "-p" ]; then
    PROD_MODE=true
fi

echo -e "${BLUE}n8n + CLI Tools Setup${NC}"
echo "======================"
if [ "$PROD_MODE" = true ]; then
    echo -e "${YELLOW}Mode: Production (with SSL)${NC}"
else
    echo "Mode: Development (local)"
fi
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Warning: .env file already exists${NC}"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Generate encryption key
encryption_key=$(openssl rand -hex 32)

# Get timezone
read -p "Timezone [America/Costa_Rica]: " timezone
timezone=${timezone:-America/Costa_Rica}

# Production-specific settings
domain_name="example.com"
subdomain="n8n"
ssl_email=""

if [ "$PROD_MODE" = true ]; then
    echo ""
    echo -e "${BLUE}Production Settings${NC}"
    echo "-------------------"

    read -p "Domain name (e.g., example.com): " domain_name
    read -p "Subdomain [n8n]: " subdomain
    subdomain=${subdomain:-n8n}

    read -p "SSL certificate email: " ssl_email

    webhook_url="https://${subdomain}.${domain_name}/"
    n8n_host="${subdomain}.${domain_name}"
    n8n_protocol="https"
else
    webhook_url="http://localhost:5678/"
    n8n_host="localhost"
    n8n_protocol="http"
fi

# ===========================================
# Integration Setup
# ===========================================
echo ""
echo -e "${BLUE}Integration Setup${NC}"
echo "-------------------"
echo "n8n connects to Google and Notion natively via built-in nodes."
echo "Credentials are configured in n8n's UI, but OAuth2 needs env vars."
echo ""

# Google OAuth2
echo -e "${YELLOW}Google OAuth2 (Gmail, Calendar, Drive)${NC}"
echo "  Setup guide: docs/google-oauth-setup.md"
echo "  GCP Console: https://console.cloud.google.com/"
echo ""
read -p "Configure Google OAuth2 now? (y/N): " setup_google
google_oauth_client_id=""
google_oauth_client_secret=""
if [ "$setup_google" = "y" ] || [ "$setup_google" = "Y" ]; then
    read -p "  Google OAuth Client ID: " google_oauth_client_id
    read -p "  Google OAuth Client Secret: " google_oauth_client_secret
    if [ "$PROD_MODE" = true ]; then
        echo -e "  ${YELLOW}Redirect URI: https://${subdomain}.${domain_name}/rest/oauth2-credential/callback${NC}"
    else
        echo -e "  ${YELLOW}Redirect URI: http://localhost:5678/rest/oauth2-credential/callback${NC}"
    fi
fi

# Notion
echo ""
echo -e "${YELLOW}Notion API${NC}"
echo "  Setup guide: docs/notion-setup.md"
echo "  Integrations: https://www.notion.so/my-integrations"
echo ""
read -p "Configure Notion now? (y/N): " setup_notion
notion_api_token=""
if [ "$setup_notion" = "y" ] || [ "$setup_notion" = "Y" ]; then
    read -p "  Notion Internal Integration Secret: " notion_api_token
fi

# Google AI API key (optional, for CLI tools)
echo ""
read -p "Google AI API Key (optional, for genimg): " google_api_key

# Create .env file
cat > .env << EOF
# n8n + CLI Tools Configuration
# Generated by setup.sh on $(date)
# Mode: $([ "$PROD_MODE" = true ] && echo "Production" || echo "Development")

# =====================================================
# Security
# =====================================================
N8N_ENCRYPTION_KEY=${encryption_key}

# =====================================================
# n8n Settings
# =====================================================
N8N_HOST=${n8n_host}
N8N_PORT=5678
N8N_PROTOCOL=${n8n_protocol}
WEBHOOK_URL=${webhook_url}
TIMEZONE=${timezone}
N8N_DIAGNOSTICS_ENABLED=false

# =====================================================
# Production Settings (SSL)
# =====================================================
DOMAIN_NAME=${domain_name}
SUBDOMAIN=${subdomain}
SSL_EMAIL=${ssl_email}

# =====================================================
# n8n Editor & Webhooks
# =====================================================
N8N_EDITOR_BASE_URL=${webhook_url}

# =====================================================
# Google OAuth2 Credentials (Gmail, Calendar, Drive)
# =====================================================
GOOGLE_OAUTH_CLIENT_ID=${google_oauth_client_id}
GOOGLE_OAUTH_CLIENT_SECRET=${google_oauth_client_secret}

# =====================================================
# Notion API
# =====================================================
NOTION_API_TOKEN=${notion_api_token}

# =====================================================
# CLI Tools Settings
# =====================================================
CLI_TOOLS_UPDATE_CHECK=true
CLI_TOOLS_AUTO_UPDATE=false

# =====================================================
# API Keys
# =====================================================
GOOGLE_AI_API_KEY=${google_api_key}
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""

if [ "$PROD_MODE" = true ]; then
    echo "Start production with:"
    echo -e "  ${GREEN}docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d${NC}"
    echo ""
    echo "Access n8n at:"
    echo "  https://${subdomain}.${domain_name}"
else
    echo "Start development with:"
    echo -e "  ${GREEN}docker-compose up -d${NC}"
    echo ""
    echo "Access n8n at:"
    echo "  http://localhost:5678"
fi

echo ""
echo -e "${YELLOW}Important: On first launch, you must create the owner account${NC}"
echo -e "${YELLOW}via the n8n web interface. This cannot be automated.${NC}"
