#!/bin/bash
# Setup script for n8n + CLI Tools
# Generates .env file with secure credentials

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}n8n + CLI Tools Setup${NC}"
echo "======================"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Warning: .env file already exists${NC}"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Get admin username
read -p "Admin username [admin]: " admin_user
admin_user=${admin_user:-admin}

# Get admin password or generate one
read -p "Admin password (leave empty to generate): " admin_password
if [ -z "$admin_password" ]; then
    admin_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo -e "${GREEN}Generated password: ${admin_password}${NC}"
fi

# Generate encryption key
encryption_key=$(openssl rand -hex 32)

# Get timezone
read -p "Timezone [America/Costa_Rica]: " timezone
timezone=${timezone:-America/Costa_Rica}

# Get Google AI API key (optional)
read -p "Google AI API Key (optional, for genimg): " google_api_key

# Create .env file
cat > .env << EOF
# n8n + CLI Tools Configuration
# Generated by setup.sh on $(date)

# =====================================================
# Admin Credentials
# =====================================================
N8N_ADMIN_USER=${admin_user}
N8N_ADMIN_PASSWORD=${admin_password}

# =====================================================
# Security
# =====================================================
N8N_ENCRYPTION_KEY=${encryption_key}

# =====================================================
# n8n Settings
# =====================================================
N8N_HOST=localhost
N8N_PORT=5678
N8N_PROTOCOL=http
WEBHOOK_URL=http://localhost:5678/
TIMEZONE=${timezone}
N8N_DIAGNOSTICS_ENABLED=false

# =====================================================
# CLI Tools Settings
# =====================================================
CLI_TOOLS_UPDATE_CHECK=true
CLI_TOOLS_AUTO_UPDATE=false

# =====================================================
# API Keys
# =====================================================
GOOGLE_AI_API_KEY=${google_api_key}
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""
echo "Your credentials:"
echo "  Username: ${admin_user}"
echo "  Password: ${admin_password}"
echo ""
echo -e "${YELLOW}Save these credentials securely!${NC}"
echo ""
echo "Start the services with:"
echo "  docker-compose up -d"
echo ""
echo "Access n8n at:"
echo "  http://localhost:5678"
