#!/bin/bash
# Setup script for n8n + CLI Tools
# Generates .env file with secure credentials
#
# Usage:
#   ./setup.sh           # Development setup
#   ./setup.sh --prod    # Production setup (with domain/SSL config)

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check for production flag
PROD_MODE=false
if [ "$1" = "--prod" ] || [ "$1" = "-p" ]; then
    PROD_MODE=true
fi

echo -e "${BLUE}n8n + CLI Tools Setup${NC}"
echo "======================"
if [ "$PROD_MODE" = true ]; then
    echo -e "${YELLOW}Mode: Production (with Traefik/SSL)${NC}"
else
    echo "Mode: Development (local)"
fi
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo -e "${YELLOW}Warning: .env file already exists${NC}"
    read -p "Overwrite? (y/N): " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Get admin username
read -p "Admin username [admin]: " admin_user
admin_user=${admin_user:-admin}

# Get admin password or generate one
read -p "Admin password (leave empty to generate): " admin_password
if [ -z "$admin_password" ]; then
    admin_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
    echo -e "${GREEN}Generated password: ${admin_password}${NC}"
fi

# Generate encryption key
encryption_key=$(openssl rand -hex 32)

# Get timezone
read -p "Timezone [America/Costa_Rica]: " timezone
timezone=${timezone:-America/Costa_Rica}

# Production-specific settings
domain_name="example.com"
subdomain="n8n"
ssl_email=""

if [ "$PROD_MODE" = true ]; then
    echo ""
    echo -e "${BLUE}Production Settings${NC}"
    echo "-------------------"

    read -p "Domain name (e.g., example.com): " domain_name
    read -p "Subdomain [n8n]: " subdomain
    subdomain=${subdomain:-n8n}

    read -p "SSL certificate email: " ssl_email

    webhook_url="https://${subdomain}.${domain_name}/"
    n8n_host="${subdomain}.${domain_name}"
    n8n_protocol="https"
else
    webhook_url="http://localhost:5678/"
    n8n_host="localhost"
    n8n_protocol="http"
fi

# Get Google AI API key (optional)
echo ""
read -p "Google AI API Key (optional, for genimg): " google_api_key

# Create .env file
cat > .env << EOF
# n8n + CLI Tools Configuration
# Generated by setup.sh on $(date)
# Mode: $([ "$PROD_MODE" = true ] && echo "Production" || echo "Development")

# =====================================================
# Admin Credentials
# =====================================================
N8N_ADMIN_USER=${admin_user}
N8N_ADMIN_PASSWORD=${admin_password}

# =====================================================
# Security
# =====================================================
N8N_ENCRYPTION_KEY=${encryption_key}

# =====================================================
# n8n Settings
# =====================================================
N8N_HOST=${n8n_host}
N8N_PORT=5678
N8N_PROTOCOL=${n8n_protocol}
WEBHOOK_URL=${webhook_url}
TIMEZONE=${timezone}
N8N_DIAGNOSTICS_ENABLED=false

# =====================================================
# Production Settings (Traefik/SSL)
# =====================================================
DOMAIN_NAME=${domain_name}
SUBDOMAIN=${subdomain}
SSL_EMAIL=${ssl_email}

# =====================================================
# CLI Tools Settings
# =====================================================
CLI_TOOLS_UPDATE_CHECK=true
CLI_TOOLS_AUTO_UPDATE=false

# =====================================================
# API Keys
# =====================================================
GOOGLE_AI_API_KEY=${google_api_key}
EOF

echo ""
echo -e "${GREEN}✓ Configuration saved to .env${NC}"
echo ""
echo "Your credentials:"
echo "  Username: ${admin_user}"
echo "  Password: ${admin_password}"
echo ""
echo -e "${YELLOW}Save these credentials securely!${NC}"
echo ""

if [ "$PROD_MODE" = true ]; then
    echo "Start production with:"
    echo -e "  ${GREEN}docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d${NC}"
    echo ""
    echo "Access n8n at:"
    echo "  https://${subdomain}.${domain_name}"
else
    echo "Start development with:"
    echo -e "  ${GREEN}docker-compose up -d${NC}"
    echo ""
    echo "Access n8n at:"
    echo "  http://localhost:5678"
fi
